"""PyPOWER Module testing

This script run all the cases in the pypower folder for both PF and OPF solutions.
All results are stored in the `case*_pf.out` and `case*_opf.out` unless there is an
exception generated by the solver itself, in which case the traceback is stored
in the file `case*.err`. If the PF fails, the OPF is not attempted.

"""

import os
import sys
import importlib
import json
import numpy as np
import traceback

MODULEDIR = ".."
CASEDIR = "../pypower"

sys.path.extend([MODULEDIR,CASEDIR])
from pypower.api import runpf, runopf, ppoption

tested = 0
failed = 0

class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super().default(obj)

print(f"Testing all cases in {CASEDIR}...")
for case in os.listdir("../pypower"):
    if case.startswith("case") and case.endswith(".py"):
        name = os.path.splitext(case)[0]
        module = importlib.__import__(name)
        try:
            if hasattr(module,name):
                tested += 1
                print(f"Running {case} pf and opf",end="... ",flush=True,file=sys.stdout)
                
                casedata = getattr(module,name)()
                json.dump(casedata,open(f"{name}.json","w"),
                    cls=NumpyEncoder,
                    indent=4)
                
                ppopt = ppoption(VERBOSE=0,OUT_ALL=0)

                result = runpf(casedata,ppopt)
                print(result,file=open(f"{name}_pf.out","w"))
                assert result[1] == 1, "runpf failed"

                if 'gencost' in casedata:
                    result = runopf(casedata,ppopt)
                    print(result,file=open(f"{name}_opf.out","w"))
                    assert result["success"], "runopf failed"

                print("ok.",file=sys.stdout)

        except Exception as err:
            print(f"ERROR [{name}]: {err}",file=sys.stderr)
            e_type,e_value,e_trace = sys.exc_info()
            with open(f"{name}.err","w") as fh:
                trace = '\n'.join(traceback.format_tb(e_trace))
                print(f"EXCEPTION [{e_type.__name__}]: {e_value}\n\n{trace}",file=fh)
            failed += 1
print(f"Testing completed: {tested=}, {failed=}")

exit(1 if failed > 0 else 0)
